// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: test1

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_patientName;
extern lv_obj_t * ui_slot;
extern lv_obj_t * ui_medication;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen2;
extern lv_obj_t * uic_patientName;
extern lv_obj_t * uic_slot;
extern lv_obj_t * uic_medication;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

