// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: test1

#include "ui.h"

lv_obj_t * uic_medication;
lv_obj_t * uic_slot;
lv_obj_t * uic_patientName;
lv_obj_t * uic_Screen2;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_patientName = NULL;
lv_obj_t * ui_slot = NULL;
lv_obj_t * ui_medication = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label3 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen2, &ui_img_screen2_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_patientName = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_patientName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_patientName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_patientName, 2);
    lv_obj_set_y(ui_patientName, 6);
    lv_obj_set_align(ui_patientName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_patientName, "Patient Name");
    lv_obj_set_style_text_font(ui_patientName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_slot = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_slot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_slot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_slot, 122);
    lv_obj_set_y(ui_slot, 41);
    lv_obj_set_align(ui_slot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_slot, "Slot:");
    lv_obj_set_style_text_font(ui_slot, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_medication = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_medication, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_medication, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_medication, -44);
    lv_obj_set_y(ui_medication, 41);
    lv_obj_set_align(ui_medication, LV_ALIGN_CENTER);
    lv_label_set_text(ui_medication, "medication");

    ui_Button1 = lv_button_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 264);
    lv_obj_set_height(ui_Button1, 36);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, 80);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x628ECB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Dispense");

    uic_Screen2 = ui_Screen2;
    uic_patientName = ui_patientName;
    uic_slot = ui_slot;
    uic_medication = ui_medication;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    uic_Screen2 = NULL;
    ui_Screen2 = NULL;
    uic_patientName = NULL;
    ui_patientName = NULL;
    uic_slot = NULL;
    ui_slot = NULL;
    uic_medication = NULL;
    ui_medication = NULL;
    ui_Button1 = NULL;
    ui_Label3 = NULL;

}
