// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: test1

#include "ui.h"

lv_obj_t * uic_uiserialLabel;
lv_obj_t * uic_timeLbl;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_timeLbl = NULL;
lv_obj_t * ui_uiserialLabel = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Screen1, &ui_img_1730212262, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeLbl = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeLbl, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLbl, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_timeLbl, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLbl, "12:00 am");
    lv_obj_set_style_text_font(ui_timeLbl, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiserialLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_uiserialLabel, 100);
    lv_obj_set_height(ui_uiserialLabel, 100);
    lv_obj_set_x(ui_uiserialLabel, -181);
    lv_obj_set_y(ui_uiserialLabel, -77);
    lv_obj_set_align(ui_uiserialLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_uiserialLabel, "ui_serialLabel");
    lv_obj_set_style_text_color(ui_uiserialLabel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_uiserialLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_uiserialLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_timeLbl = ui_timeLbl;
    uic_uiserialLabel = ui_uiserialLabel;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_timeLbl = NULL;
    ui_timeLbl = NULL;
    uic_uiserialLabel = NULL;
    ui_uiserialLabel = NULL;

}
